WaktuGeneralException: renamed to WaktuException since we plan to use only one exception, moved to service package to avoid access to higher level packages